package view;

import controller.*;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import model.*;

public class MainFrame extends javax.swing.JFrame {
    public Client client;

    public MainFrame(Client client, boolean role) {
        initComponents();
        
        if (!role) {
            tab.setEnabledAt(1, false);
            this.btn_sw_chat.doClick();
            this.btn_sw_management.setVisible(false);
            this.btn_sw_chat.setVisible(false);
        }
        
        
        this.client = client;
        this.setTitle(client.username);
        this.dl_file_download.setLocationRelativeTo(null);
        this.lb_user_identify.setText("You are Logged as: " + client.username);
        this.btn_get_users.doClick();
        this.receiveMessage();
        this.setVisible(true);
    }
    
    public void receiveMessage() {
        new Thread(new Runnable() {
            public void run() {
                while (true) {
                    try {
                        ta_chat_log.append(MessageController.messageDecrypt((String) client.blockingQueue_receive.take()) + "\n");
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        }).start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dl_file_download = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_file_name = new javax.swing.JList<>();
        btn_download_result = new javax.swing.JLabel();
        tf_download_source = new javax.swing.JTextField();
        btn_download_change_directory = new javax.swing.JButton();
        btn_download_submit = new javax.swing.JButton();
        tab = new javax.swing.JTabbedPane();
        tab_chat = new javax.swing.JPanel();
        javax.swing.JScrollPane chat_log = new javax.swing.JScrollPane();
        ta_chat_log = new javax.swing.JTextArea();
        btn_send = new javax.swing.JButton();
        tf_input = new javax.swing.JTextField();
        tf_key = new javax.swing.JTextField();
        lb_user_identify = new javax.swing.JLabel();
        javax.swing.JLabel lb_key = new javax.swing.JLabel();
        btn_upload = new javax.swing.JButton();
        btn_download = new javax.swing.JButton();
        tab_management = new javax.swing.JPanel();
        table = new javax.swing.JScrollPane();
        tb_data = new javax.swing.JTable();
        btn_get_users = new javax.swing.JButton();
        btn_add_user = new javax.swing.JToggleButton();
        tf_info_username = new javax.swing.JTextField();
        tf_info_password = new javax.swing.JTextField();
        tf_info_role = new javax.swing.JTextField();
        tf_info_name = new javax.swing.JTextField();
        tf_info_phone_number = new javax.swing.JTextField();
        tf_info_email = new javax.swing.JTextField();
        javax.swing.JLabel lb_info_username = new javax.swing.JLabel();
        lb_info_name = new javax.swing.JLabel();
        lb_info_role = new javax.swing.JLabel();
        lb_info_password = new javax.swing.JLabel();
        lb_info_email = new javax.swing.JLabel();
        lb_info_phone = new javax.swing.JLabel();
        btn_delete_user = new javax.swing.JButton();
        btn_edit_user = new javax.swing.JButton();
        btn_clear_chat_db = new javax.swing.JButton();
        lb_query_result = new javax.swing.JLabel();
        btn_sw_management = new javax.swing.JButton();
        btn_sw_chat = new javax.swing.JButton();
        btn_clear_chat_log = new javax.swing.JButton();
        btn_show_chat_log = new javax.swing.JButton();
        javax.swing.JLabel lb_background = new javax.swing.JLabel();

        dl_file_download.setTitle("Download File");
        dl_file_download.setMinimumSize(new java.awt.Dimension(423, 300));
        dl_file_download.setResizable(false);

        list_file_name.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        list_file_name.setForeground(new java.awt.Color(255, 255, 255));
        list_file_name.setModel(StorageController.getFilesNameList());
        list_file_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_file_nameMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list_file_name);

        btn_download_result.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        btn_download_result.setText("Please choose the File you want to download");

        btn_download_change_directory.setText("Directory");
        btn_download_change_directory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_download_change_directoryActionPerformed(evt);
            }
        });

        btn_download_submit.setText("Download");
        btn_download_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_download_submitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout dl_file_downloadLayout = new javax.swing.GroupLayout(dl_file_download.getContentPane());
        dl_file_download.getContentPane().setLayout(dl_file_downloadLayout);
        dl_file_downloadLayout.setHorizontalGroup(
            dl_file_downloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dl_file_downloadLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(dl_file_downloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_download_source, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_download_result)
                    .addGroup(dl_file_downloadLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(dl_file_downloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_download_change_directory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_download_submit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        dl_file_downloadLayout.setVerticalGroup(
            dl_file_downloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dl_file_downloadLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(tf_download_source, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(dl_file_downloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(dl_file_downloadLayout.createSequentialGroup()
                        .addComponent(btn_download_change_directory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_download_submit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_download_result)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tab_chat.setBackground(new java.awt.Color(0, 0, 0));
        tab_chat.setOpaque(false);

        ta_chat_log.setEditable(false);
        ta_chat_log.setBackground(new java.awt.Color(51, 51, 51));
        ta_chat_log.setColumns(20);
        ta_chat_log.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        ta_chat_log.setRows(5);
        ta_chat_log.setBorder(null);
        chat_log.setViewportView(ta_chat_log);

        btn_send.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        btn_send.setText("Send");
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });

        tf_input.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        tf_input.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_inputKeyPressed(evt);
            }
        });

        tf_key.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N

        lb_user_identify.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        lb_user_identify.setForeground(new java.awt.Color(255, 255, 255));
        lb_user_identify.setText("You are Logged as:");

        lb_key.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        lb_key.setForeground(new java.awt.Color(255, 255, 255));
        lb_key.setText("Key:");

        btn_upload.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        btn_upload.setText("Upload File");
        btn_upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_uploadActionPerformed(evt);
            }
        });

        btn_download.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        btn_download.setText("Download File");
        btn_download.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_downloadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tab_chatLayout = new javax.swing.GroupLayout(tab_chat);
        tab_chat.setLayout(tab_chatLayout);
        tab_chatLayout.setHorizontalGroup(
            tab_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_chatLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tab_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_chatLayout.createSequentialGroup()
                        .addComponent(tf_input, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_chatLayout.createSequentialGroup()
                        .addComponent(btn_upload, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_download)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_key)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_key, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tab_chatLayout.createSequentialGroup()
                        .addGroup(tab_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_user_identify, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chat_log, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        tab_chatLayout.setVerticalGroup(
            tab_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tab_chatLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lb_user_identify)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chat_log, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tab_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_key)
                    .addComponent(btn_upload)
                    .addComponent(btn_download))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tab_chatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_send))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        tab.addTab("Chat", tab_chat);

        tab_management.setOpaque(false);

        tb_data.setFont(new java.awt.Font("JetBrains Mono", 1, 10)); // NOI18N
        tb_data.setForeground(new java.awt.Color(255, 255, 255));
        tb_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tb_data.getTableHeader().setReorderingAllowed(false);
        tb_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_dataMouseClicked(evt);
            }
        });
        table.setViewportView(tb_data);

        btn_get_users.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        btn_get_users.setForeground(new java.awt.Color(255, 255, 255));
        btn_get_users.setText("Reload table");
        btn_get_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_get_usersActionPerformed(evt);
            }
        });

        btn_add_user.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        btn_add_user.setForeground(new java.awt.Color(255, 255, 255));
        btn_add_user.setText("Add User");
        btn_add_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_userActionPerformed(evt);
            }
        });

        tf_info_username.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N

        tf_info_password.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N

        tf_info_role.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N

        tf_info_name.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        tf_info_name.setMinimumSize(new java.awt.Dimension(32, 23));

        tf_info_phone_number.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N

        tf_info_email.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N

        lb_info_username.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        lb_info_username.setForeground(new java.awt.Color(255, 255, 255));
        lb_info_username.setText("Username:");

        lb_info_name.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        lb_info_name.setForeground(new java.awt.Color(255, 255, 255));
        lb_info_name.setText("Name:");

        lb_info_role.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        lb_info_role.setForeground(new java.awt.Color(255, 255, 255));
        lb_info_role.setText("Role:");

        lb_info_password.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        lb_info_password.setForeground(new java.awt.Color(255, 255, 255));
        lb_info_password.setText("Password:");

        lb_info_email.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        lb_info_email.setForeground(new java.awt.Color(255, 255, 255));
        lb_info_email.setText("Email:");

        lb_info_phone.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        lb_info_phone.setForeground(new java.awt.Color(255, 255, 255));
        lb_info_phone.setText("Phone number:");

        btn_delete_user.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        btn_delete_user.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete_user.setText("Delete User");
        btn_delete_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_userActionPerformed(evt);
            }
        });

        btn_edit_user.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        btn_edit_user.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit_user.setText("Edit User");
        btn_edit_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_userActionPerformed(evt);
            }
        });

        btn_clear_chat_db.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        btn_clear_chat_db.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear_chat_db.setText("Clear Chat History");
        btn_clear_chat_db.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear_chat_dbActionPerformed(evt);
            }
        });

        lb_query_result.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        lb_query_result.setForeground(new java.awt.Color(255, 255, 255));
        lb_query_result.setText("Get Users Successfully");

        javax.swing.GroupLayout tab_managementLayout = new javax.swing.GroupLayout(tab_management);
        tab_management.setLayout(tab_managementLayout);
        tab_managementLayout.setHorizontalGroup(
            tab_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_managementLayout.createSequentialGroup()
                .addGroup(tab_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tab_managementLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(tab_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(tab_managementLayout.createSequentialGroup()
                                    .addComponent(lb_info_username)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tf_info_username, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(tab_managementLayout.createSequentialGroup()
                                    .addGap(2, 2, 2)
                                    .addGroup(tab_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(tab_managementLayout.createSequentialGroup()
                                            .addGroup(tab_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(tab_managementLayout.createSequentialGroup()
                                                    .addComponent(lb_info_role)
                                                    .addGap(33, 33, 33)
                                                    .addComponent(tf_info_role))
                                                .addGroup(tab_managementLayout.createSequentialGroup()
                                                    .addComponent(lb_info_password)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tf_info_password, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGap(18, 18, 18)
                                            .addGroup(tab_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(tab_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(tab_managementLayout.createSequentialGroup()
                                                        .addComponent(lb_info_email)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tf_info_email, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(tab_managementLayout.createSequentialGroup()
                                                        .addComponent(lb_info_name)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(tf_info_name, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(tab_managementLayout.createSequentialGroup()
                                                    .addComponent(lb_info_phone)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(tf_info_phone_number))))
                                        .addGroup(tab_managementLayout.createSequentialGroup()
                                            .addGroup(tab_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(btn_get_users, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btn_add_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(18, 18, 18)
                                            .addGroup(tab_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(tab_managementLayout.createSequentialGroup()
                                                    .addComponent(btn_delete_user, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(btn_edit_user, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(btn_clear_chat_db)))))))
                        .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb_query_result))
                .addGap(0, 123, Short.MAX_VALUE))
        );
        tab_managementLayout.setVerticalGroup(
            tab_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tab_managementLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(tab_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tab_managementLayout.createSequentialGroup()
                        .addGroup(tab_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_info_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_info_username))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tab_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_info_password)
                            .addComponent(tf_info_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tab_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_info_role)
                            .addGroup(tab_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tf_info_role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_info_phone)
                                .addComponent(tf_info_phone_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(tab_managementLayout.createSequentialGroup()
                        .addGroup(tab_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_info_name)
                            .addComponent(tf_info_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tab_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_info_email)
                            .addComponent(tf_info_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(tab_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_add_user)
                    .addComponent(btn_delete_user)
                    .addComponent(btn_edit_user))
                .addGap(18, 18, 18)
                .addGroup(tab_managementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_get_users)
                    .addComponent(btn_clear_chat_db))
                .addGap(18, 18, 18)
                .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_query_result)
                .addGap(48, 48, 48))
        );

        tab.addTab("Management", tab_management);

        getContentPane().add(tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, -39, -1, 540));

        btn_sw_management.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        btn_sw_management.setForeground(new java.awt.Color(255, 255, 255));
        btn_sw_management.setText("Management");
        btn_sw_management.setBorderPainted(false);
        btn_sw_management.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sw_managementActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sw_management, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 140, 50));

        btn_sw_chat.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        btn_sw_chat.setForeground(new java.awt.Color(255, 255, 255));
        btn_sw_chat.setText("Chat Room");
        btn_sw_chat.setBorderPainted(false);
        btn_sw_chat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sw_chatActionPerformed(evt);
            }
        });
        getContentPane().add(btn_sw_chat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 140, 50));

        btn_clear_chat_log.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        btn_clear_chat_log.setForeground(new java.awt.Color(255, 255, 255));
        btn_clear_chat_log.setText("Clear Chat Log");
        btn_clear_chat_log.setBorderPainted(false);
        btn_clear_chat_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clear_chat_logActionPerformed(evt);
            }
        });
        getContentPane().add(btn_clear_chat_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 140, 50));

        btn_show_chat_log.setFont(new java.awt.Font("JetBrains Mono", 0, 12)); // NOI18N
        btn_show_chat_log.setForeground(new java.awt.Color(255, 255, 255));
        btn_show_chat_log.setText("Show Chat Log");
        btn_show_chat_log.setOpaque(true);
        btn_show_chat_log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_show_chat_logActionPerformed(evt);
            }
        });
        getContentPane().add(btn_show_chat_log, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 140, 50));

        lb_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/milad-fakurian-iLHDO19h0ng-unsplash.jpg"))); // NOI18N
        getContentPane().add(lb_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        // TODO add your handling code here:
        Message message = new Message(client.username, tf_input.getText(), tf_key.getText());
        
        try {
            if (client.socket != null && !client.socket.isClosed()) {
                ta_chat_log.append(message.messageShow() + "\n");
                client.blockingQueue_send.put(message);
            } else {
                ta_chat_log.append("Can't send the message. Server is offline\n");
            }
            
            tf_input.setText("");
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_sendActionPerformed

    private void btn_sw_chatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sw_chatActionPerformed
        // TODO add your handling code here:
        tab.setSelectedIndex(0);
    }//GEN-LAST:event_btn_sw_chatActionPerformed

    private void btn_sw_managementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sw_managementActionPerformed
        // TODO add your handling code here:
        tab.setSelectedIndex(1);
    }//GEN-LAST:event_btn_sw_managementActionPerformed

    private void btn_get_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_get_usersActionPerformed
        // TODO add your handling code here:
        try {
            this.tb_data.setModel(UserController.getUsersTable());
            lb_query_result.setText("Get Users Successfully!");
        } catch (Exception e) {
            lb_query_result.setText("Cant get Users! Unkown Error!");
        }
    }//GEN-LAST:event_btn_get_usersActionPerformed

    private void tb_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_dataMouseClicked
        // TODO add your handling code here:
        int row = tb_data.getSelectedRow();
        
        try {
            tf_info_username.setText(tb_data.getModel().getValueAt(row, 0).toString());
            tf_info_password.setText(tb_data.getModel().getValueAt(row, 1).toString());
            tf_info_role.setText(tb_data.getModel().getValueAt(row, 2).toString());
            tf_info_name.setText(tb_data.getModel().getValueAt(row, 3).toString());
            tf_info_email.setText(tb_data.getModel().getValueAt(row, 4).toString());
            tf_info_phone_number.setText(tb_data.getModel().getValueAt(row, 5).toString());
        } catch (Exception e) {
            lb_query_result.setText("Cant get record information! Unkown Error!");
        }
    }//GEN-LAST:event_tb_dataMouseClicked

    private void btn_show_chat_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_show_chat_logActionPerformed
        // TODO add your handling code here:
        try {
            ArrayList <String> data = MessageController.getMessages();
            ta_chat_log.setText("");
            
            for (String message : data) {
                ta_chat_log.append(message + "\n");
            }
        } catch (Exception e) {
            e.printStackTrace();
            ta_chat_log.append("Cant load the chat log! Unknown Error!");
        }
    }//GEN-LAST:event_btn_show_chat_logActionPerformed

    private void btn_clear_chat_logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear_chat_logActionPerformed
        // TODO add your handling code here:
        ta_chat_log.setText("");
        ta_chat_log.append("Chat Log has been clear!");
    }//GEN-LAST:event_btn_clear_chat_logActionPerformed

    private void tf_inputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_inputKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btn_send.doClick();
        }
    }//GEN-LAST:event_tf_inputKeyPressed

    private void btn_add_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_userActionPerformed
        // TODO add your handling code here:
        if (UserController.createUser(
            tf_info_username.getText(), 
            tf_info_password.getText(), 
            Boolean.parseBoolean(tf_info_role.getText()), 
            tf_info_name.getText(), 
            tf_info_email.getText(), 
            tf_info_phone_number.getText())) {
            btn_get_users.doClick();
            lb_query_result.setText("Add Users Successfully!");
        } else {
            lb_query_result.setText("Cant add user! Unkown Error!");
        }
    }//GEN-LAST:event_btn_add_userActionPerformed

    private void btn_delete_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_userActionPerformed
        // TODO add your handling code here:
        if (UserController.isOnline(tf_info_username.getText())) {
            lb_query_result.setText("Cant delete '" + tf_info_username.getText() +"' because it is online!");
        } else if (tf_info_username.getText().equals("Server")) {
            lb_query_result.setText("Cant delete Server!");
        } else if (!UserController.isExist(tf_info_username.getText())) {
            lb_query_result.setText("Cant find '" + tf_info_username.getText() +"' to delete!");
        } else if (UserController.removeUser(tf_info_username.getText())){
            btn_get_users.doClick();
            lb_query_result.setText("Delete Users Successfully!");
        } else {
            lb_query_result.setText("Cant delete user! Unkown Error!");
        }
    }//GEN-LAST:event_btn_delete_userActionPerformed

    private void btn_edit_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_userActionPerformed
        // TODO add your handling code here:
        if (!UserController.isExist(tf_info_username.getText())) {
            lb_query_result.setText("Cant edit user! User not found!");
        } else if (UserController.removeUser(tf_info_username.getText())) {
            UserController.createUser(
            tf_info_username.getText(), 
            tf_info_password.getText(), 
            Boolean.parseBoolean(tf_info_role.getText()), 
            tf_info_name.getText(), 
            tf_info_email.getText(), 
            tf_info_phone_number.getText());
                    
            btn_get_users.doClick();
            lb_query_result.setText("Edit Users Successfully!");
        } else {
            lb_query_result.setText("Cant edit user! Unkown Error!");
        }
    }//GEN-LAST:event_btn_edit_userActionPerformed

    private void btn_clear_chat_dbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clear_chat_dbActionPerformed
        // TODO add your handling code here:
        if (MessageController.deleteMessages()) {
            lb_query_result.setText("Delete all messages successfully");
        } else {
            lb_query_result.setText("Cant delete all messages! Unkown Error!");
        }
    }//GEN-LAST:event_btn_clear_chat_dbActionPerformed

    private void btn_uploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_uploadActionPerformed
        Client file_sender_client = new Client(1);
        
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            
            if (file_sender_client.sendFile(selectedFile)) {
                ta_chat_log.append("File " + selectedFile.getName() + " is sent\n");
            } else {
                ta_chat_log.append("Unknown errors! Cant send " + selectedFile.getName());
            }
        }
    }//GEN-LAST:event_btn_uploadActionPerformed

    private void btn_downloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_downloadActionPerformed
        // TODO add your handling code here:
        list_file_name.setModel(StorageController.getFilesNameList());
        btn_download_result.setText("Please choose the File you want to download");
        dl_file_download.setVisible(true);
    }//GEN-LAST:event_btn_downloadActionPerformed

    private void list_file_nameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_file_nameMouseClicked
        // TODO add your handling code here:
        String fileName = (String) list_file_name.getSelectedValue();
        btn_download_result.setText("You are selecting " + fileName);
    }//GEN-LAST:event_list_file_nameMouseClicked

    private void btn_download_change_directoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_download_change_directoryActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = fileChooser.showOpenDialog(this);
        
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFolder = fileChooser.getSelectedFile();
            tf_download_source.setText(selectedFolder.getAbsolutePath());
        }
    }//GEN-LAST:event_btn_download_change_directoryActionPerformed

    private void btn_download_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_download_submitActionPerformed
        // TODO add your handling code here:
        Client file_receiver_client = new Client(2);

        try {
            if (((String) list_file_name.getSelectedValue()).equals("")) {
                // nothing - jump to catch
            } else if (tf_download_source.getText().equals("")) {
                btn_download_result.setText("Please choose directory of the download file");
            } else {
                file_receiver_client.receiveFile(tf_download_source.getText(), (String) list_file_name.getSelectedValue());
            }
        } catch (Exception e) {
            btn_download_result.setText("Please choose the file you want to download");
        }
        

    }//GEN-LAST:event_btn_download_submitActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_add_user;
    private javax.swing.JButton btn_clear_chat_db;
    private javax.swing.JButton btn_clear_chat_log;
    private javax.swing.JButton btn_delete_user;
    private javax.swing.JButton btn_download;
    private javax.swing.JButton btn_download_change_directory;
    private javax.swing.JLabel btn_download_result;
    private javax.swing.JButton btn_download_submit;
    private javax.swing.JButton btn_edit_user;
    private javax.swing.JButton btn_get_users;
    private javax.swing.JButton btn_send;
    private javax.swing.JButton btn_show_chat_log;
    private javax.swing.JButton btn_sw_chat;
    private javax.swing.JButton btn_sw_management;
    private javax.swing.JButton btn_upload;
    private javax.swing.JDialog dl_file_download;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_info_email;
    private javax.swing.JLabel lb_info_name;
    private javax.swing.JLabel lb_info_password;
    private javax.swing.JLabel lb_info_phone;
    private javax.swing.JLabel lb_info_role;
    private javax.swing.JLabel lb_query_result;
    private javax.swing.JLabel lb_user_identify;
    private javax.swing.JList<String> list_file_name;
    private javax.swing.JTextArea ta_chat_log;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JPanel tab_chat;
    private javax.swing.JPanel tab_management;
    private javax.swing.JScrollPane table;
    private javax.swing.JTable tb_data;
    private javax.swing.JTextField tf_download_source;
    private javax.swing.JTextField tf_info_email;
    private javax.swing.JTextField tf_info_name;
    private javax.swing.JTextField tf_info_password;
    private javax.swing.JTextField tf_info_phone_number;
    private javax.swing.JTextField tf_info_role;
    private javax.swing.JTextField tf_info_username;
    private javax.swing.JTextField tf_input;
    private javax.swing.JTextField tf_key;
    // End of variables declaration//GEN-END:variables
}
