package view;
import controller.*;
import model.*;

public class MainFrame extends javax.swing.JFrame {
    public Client client;
    /**
     * Creates new form Chat
     */
    public MainFrame(Client client) {
        this.client = client;
        initComponents();
        receive();
        this.setTitle(client.username);
        this.userIdentify.setText("You are Logged as:\n" + client.username);
        setVisible(true);
    }
    
    public void receive() {
        new Thread(new Runnable() {
            public void run() {
                while (true) {
                    try {
                        table.append(client.blockingQueue_receive.take() + "\n");
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        }).start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new javax.swing.JTabbedPane();
        chat_tab = new javax.swing.JPanel();
        javax.swing.JScrollPane ScrollPanel = new javax.swing.JScrollPane();
        table = new javax.swing.JTextArea();
        enter = new javax.swing.JButton();
        input = new javax.swing.JTextField();
        key = new javax.swing.JTextField();
        userIdentify = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chat_tab.setBackground(new java.awt.Color(0, 0, 0));
        chat_tab.setOpaque(false);

        table.setEditable(false);
        table.setColumns(20);
        table.setRows(5);
        ScrollPanel.setViewportView(table);

        enter.setText("enter");
        enter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterActionPerformed(evt);
            }
        });

        key.setText("KEY");

        userIdentify.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userIdentify.setText("You are Logged as:");

        javax.swing.GroupLayout chat_tabLayout = new javax.swing.GroupLayout(chat_tab);
        chat_tab.setLayout(chat_tabLayout);
        chat_tabLayout.setHorizontalGroup(
            chat_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chat_tabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(chat_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chat_tabLayout.createSequentialGroup()
                        .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(enter, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(key, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userIdentify, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        chat_tabLayout.setVerticalGroup(
            chat_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, chat_tabLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(userIdentify)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(key, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(chat_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enter))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        tab.addTab("Chat", chat_tab);

        getContentPane().add(tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, -39, -1, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void enterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterActionPerformed
        // TODO add your handling code here:
        Message message = new Message(client.username, input.getText(), "Some key");
        
        try {
            if (client.socket != null && !client.socket.isClosed()) {
                table.append(message.messageShow() + "\n");
                client.blockingQueue_send.put(message);
            } else {
                table.append("Can't send the message. Server is offline\n");
            }
            input.setText("");
        } catch (InterruptedException e) {
        }
    }//GEN-LAST:event_enterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel chat_tab;
    private javax.swing.JButton enter;
    private javax.swing.JTextField input;
    private javax.swing.JTextField key;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTextArea table;
    private javax.swing.JLabel userIdentify;
    // End of variables declaration//GEN-END:variables
}
